sequenceDiagram
 participant browser
 participant server

 browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
 activate server
 server-->>browser: HTML document
 deactivate server

 browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
 activate server
 server-->>browser: CSS file
 deactivate server

 browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
 activate server
 server-->>browser: JavaScript file
 deactivate server

 Note right of browser: Browser starts executing the JavaScript

 browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
 activate server
 server-->>browser: JSON data [{ content: "10", date: "2025-07-14T10:14:27.168Z" }, ...]
 deactivate server

 Note right of browser: Browser parses JSON and renders notes into HTML