sequenceDiagram
 participant browser
 participant server

 Note right of browser: User creates a note and submits the form
 Note right of browser: JavaScript handles the submit event, updates the DOM without reloading

 browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa 
 activate server
 server-->>browser: 201 Created
 deactivate server

 Note right of browser: Browser logs the server's response
